import type { SandboxAction } from "@autochain/shared";

export const SANDBOX_ACTIONS: SandboxAction[] = [
  {
    key: "navigate.dashboard",
    label: "Open Dashboard",
    description: "Navigate to the customer dashboard",
    route: "/dashboard",
    dataAgentId: "nav-dashboard",
    actionType: "navigate",
    sideEffect: false,
    requiresApproval: false,
    roles: ["customer", "admin"],
    tags: ["dashboard", "summary", "overview"],
  },
  {
    key: "navigate.vendor.dashboard",
    label: "Open Vendor Dashboard",
    description: "Navigate to the vendor dashboard",
    route: "/vendor/dashboard",
    dataAgentId: "nav-vendor-dashboard",
    actionType: "navigate",
    sideEffect: false,
    requiresApproval: false,
    roles: ["vendor", "admin"],
    tags: ["vendor", "dashboard", "overview"],
  },
  {
    key: "navigate.vendor.purchase-orders",
    label: "Open Vendor Purchase Orders",
    description: "Navigate to the vendor purchase orders page",
    route: "/vendor/purchase-orders",
    dataAgentId: "nav-vendor-purchase-orders",
    actionType: "navigate",
    sideEffect: false,
    requiresApproval: false,
    roles: ["vendor", "admin"],
    tags: ["vendor", "purchase-order", "procurement"],
  },
  {
    key: "navigate.vendor.catalog",
    label: "Open Vendor Catalog",
    description: "Navigate to the vendor catalog page",
    route: "/vendor/catalog",
    dataAgentId: "nav-vendor-catalog",
    actionType: "navigate",
    sideEffect: false,
    requiresApproval: false,
    roles: ["vendor", "admin"],
    tags: ["vendor", "catalog", "availability"],
  },
  {
    key: "navigate.vendor.invoices",
    label: "Open Vendor Invoices",
    description: "Navigate to the vendor invoices page",
    route: "/vendor/invoices",
    dataAgentId: "nav-vendor-invoices",
    actionType: "navigate",
    sideEffect: false,
    requiresApproval: false,
    roles: ["vendor", "admin"],
    tags: ["vendor", "invoices", "payables"],
  },
  {
    key: "navigate.products",
    label: "Open Products",
    description: "Navigate to the product catalog",
    route: "/products",
    dataAgentId: "nav-products",
    actionType: "navigate",
    sideEffect: false,
    requiresApproval: false,
    roles: ["customer"],
    tags: ["products", "inventory", "catalog"],
  },
  {
    key: "navigate.orders",
    label: "Open Orders",
    description: "Navigate to the orders page",
    route: "/orders",
    dataAgentId: "nav-orders",
    actionType: "navigate",
    sideEffect: false,
    requiresApproval: false,
    roles: ["customer"],
    tags: ["orders", "reports"],
  },
  {
    key: "navigate.invoices",
    label: "Open Invoices",
    description: "Navigate to the invoices page",
    route: "/invoices",
    dataAgentId: "nav-invoices",
    actionType: "navigate",
    sideEffect: false,
    requiresApproval: false,
    roles: ["customer"],
    tags: ["invoices", "finance", "overdue"],
  },
  {
    key: "navigate.documents",
    label: "Open Document Studio",
    description: "Navigate to the document studio",
    route: "/documents",
    dataAgentId: "nav-documents",
    actionType: "navigate",
    sideEffect: false,
    requiresApproval: false,
    roles: ["customer", "admin"],
    tags: ["documents", "reports", "agreements"],
  },
  {
    key: "navigate.workflows",
    label: "Open Workflow Console",
    description: "Navigate to the workflow console",
    route: "/workflows",
    dataAgentId: "nav-workflows",
    actionType: "navigate",
    sideEffect: false,
    requiresApproval: false,
    roles: ["customer", "admin"],
    tags: ["workflow", "agent", "automation"],
  },
  {
    key: "navigate.admin.dashboard",
    label: "Open Admin Dashboard",
    description: "Navigate to the admin dashboard",
    route: "/admin/dashboard",
    dataAgentId: "nav-admin-dashboard",
    actionType: "navigate",
    sideEffect: false,
    requiresApproval: false,
    roles: ["admin"],
    tags: ["admin", "dashboard", "ops"],
  },
  {
    key: "navigate.admin.users",
    label: "Open Admin Users",
    description: "Navigate to admin user management",
    route: "/admin/users",
    dataAgentId: "nav-admin-users",
    actionType: "navigate",
    sideEffect: false,
    requiresApproval: false,
    roles: ["admin"],
    tags: ["admin", "users", "accounts"],
  },
  {
    key: "navigate.admin.sessions",
    label: "Open Admin Sessions",
    description: "Navigate to admin session management",
    route: "/admin/sessions",
    dataAgentId: "nav-admin-sessions",
    actionType: "navigate",
    sideEffect: false,
    requiresApproval: false,
    roles: ["admin"],
    tags: ["admin", "sessions", "security"],
  },
  {
    key: "report.generate_monthly",
    label: "Generate Monthly Summary",
    description: "Generate a monthly operational summary document",
    route: "/documents",
    dataAgentId: "doc-generate-monthly",
    actionType: "generate",
    sideEffect: true,
    requiresApproval: true,
    roles: ["customer", "admin"],
    tags: ["monthly", "report", "summary"],
  },
  {
    key: "report.vendor_monthly",
    label: "Generate Vendor Ops Summary",
    description: "Generate a vendor operations summary document",
    route: "/documents",
    dataAgentId: "doc-generate-vendor-monthly",
    actionType: "generate",
    sideEffect: true,
    requiresApproval: true,
    roles: ["vendor", "admin"],
    tags: ["vendor", "monthly", "operations"],
  },
  {
    key: "report.check_overdue_invoices",
    label: "Check Overdue Invoices",
    description: "Generate an overdue invoice review report",
    route: "/documents",
    dataAgentId: "doc-generate-overdue",
    actionType: "generate",
    sideEffect: true,
    requiresApproval: true,
    roles: ["customer", "admin"],
    tags: ["invoice", "overdue", "finance"],
  },
  {
    key: "report.vendor_invoice_review",
    label: "Generate Vendor Invoice Review",
    description: "Generate a vendor invoice and payable review",
    route: "/documents",
    dataAgentId: "doc-generate-vendor-invoices",
    actionType: "generate",
    sideEffect: true,
    requiresApproval: true,
    roles: ["vendor", "admin"],
    tags: ["vendor", "invoice", "payables"],
  },
  {
    key: "report.inventory_reorder",
    label: "Generate Inventory Reorder Suggestions",
    description: "Generate a reorder recommendation report",
    route: "/documents",
    dataAgentId: "doc-generate-reorder",
    actionType: "generate",
    sideEffect: true,
    requiresApproval: true,
    roles: ["customer", "admin"],
    tags: ["inventory", "reorder", "products"],
  },
  {
    key: "report.vendor_catalog_health",
    label: "Generate Vendor Catalog Health Report",
    description: "Generate a vendor catalog health and constraint report",
    route: "/documents",
    dataAgentId: "doc-generate-vendor-catalog",
    actionType: "generate",
    sideEffect: true,
    requiresApproval: true,
    roles: ["vendor", "admin"],
    tags: ["vendor", "catalog", "constraints"],
  },
  {
    key: "report.customer_risk",
    label: "Generate Customer Risk Report",
    description: "Generate an admin-only customer risk report",
    route: "/documents",
    dataAgentId: "doc-generate-risk",
    actionType: "generate",
    sideEffect: true,
    requiresApproval: true,
    roles: ["admin"],
    tags: ["risk", "customer", "admin"],
  },
  {
    key: "document.generate_agreement",
    label: "Generate Agreement Draft",
    description: "Generate a draft agreement document",
    route: "/documents",
    dataAgentId: "doc-generate-agreement",
    actionType: "generate",
    sideEffect: true,
    requiresApproval: true,
    roles: ["customer", "vendor", "admin"],
    tags: ["agreement", "contract", "document"],
  },
  {
    key: "connector.gmail.compose",
    label: "Prepare Gmail Draft",
    description: "Prepare a Gmail draft through the connector layer",
    route: "/workflows",
    dataAgentId: "connector-gmail-compose",
    actionType: "connector",
    sideEffect: true,
    requiresApproval: true,
    roles: ["admin"],
    tags: ["gmail", "email", "connector"],
  },
  {
    key: "session.review_risky",
    label: "Review Risky Sessions",
    description: "Review risky sessions and operator recommendations",
    route: "/admin/sessions",
    dataAgentId: "session-review-risky",
    actionType: "query",
    sideEffect: false,
    requiresApproval: false,
    roles: ["admin"],
    tags: ["session", "risk", "security"],
  },
  {
    key: "session.revoke",
    label: "Revoke Session",
    description: "Revoke a selected session inside the app sandbox",
    route: "/admin/sessions",
    dataAgentId: "session-revoke",
    actionType: "mutate",
    sideEffect: true,
    requiresApproval: true,
    roles: ["admin"],
    tags: ["session", "revoke", "security"],
  },
  {
    key: "user.disable",
    label: "Disable User",
    description: "Disable a selected user account inside the app sandbox",
    route: "/admin/users",
    dataAgentId: "user-disable",
    actionType: "mutate",
    sideEffect: true,
    requiresApproval: true,
    roles: ["admin"],
    tags: ["user", "disable", "security"],
  },
];

export function getAllowedSandboxActions(
  role: "customer" | "vendor" | "admin",
) {
  return SANDBOX_ACTIONS.filter((action) => action.roles.includes(role));
}

export function getSandboxAction(key: string) {
  return SANDBOX_ACTIONS.find((action) => action.key === key);
}
